### ISSUE TITLE
All of projects labeled as "(No project)"

### ISSUE THREAD

**Issue by alerezaaa** [mcndt/obsidian-toggl-integration#153]
Hi

in inline mode with this code

````
```
```
````

**Comment by charlesthomas** [comment]
@alerezaaa i just had this, too

it's a problem with initial setup. [the fix is described here](https://github.com/mcndt/obsidian-toggl-integration/issues/125#issue-1662851626) but the tl;dr is cut and paste your api token again and then it should start working

**Comment by Grievous-Spinout** [comment]
I have a similar issue and the link did not fix it unfortunately.
some tasks come back as having no project, but not all (and all tasks have projects in toggl) when I check the error log I see the following:

![image](https://github.com/user-attachments/assets/50162a46-4aa0-48a7-9152-37e2f62616e6)


app.js:1 
TypeError: Cannot read properties of undefined (reading 'p')
    at Object.p (plugin:obsidian-togg…ntegration:21138:45)
    at update (plugin:obsidian-togg…ntegration:11753:32)
    at flush (plugin:obsidian-togg…integration:11724:7)
    at init (plugin:obsidian-togg…integration:12063:5)
    at new TogglReportBlock (plugin:obsidian-togg…integration:19461:5)
    at reportBlockHandler (plugin:obsidian-togg…integration:19471:3)
    at t.initDOM (app.js:1:1766603)
    at t.toDOM (app.js:1:1223235)
    at t.sync (app.js:1:331514)
    at e.sync (app.js:1:313111)
    at app.js:1:354441
    at e.ignore (app.js:1:435059)
    at t.updateInner (app.js:1:354223)
    at t.update (app.js:1:353978)
    at e.update (app.js:1:443807)
    at e.dispatchTransactions (app.js:1:440368)
    at e.dispatch (app.js:1:442356)
    at t.set (app.js:1:1621362)
    at t.set (app.js:1:2421677)
    at t.setViewData (app.js:1:2437148)
    at t.setData (app.js:1:2080978)
    at t.<anonymous> (app.js:1:2080881)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
    
plugin:obsidian-toggl-integration:21138 Uncaught 
TypeError: Cannot read properties of undefined (reading 'p')
    at Object.p (plugin:obsidian-togg…ntegration:21138:45)
    at update (plugin:obsidian-togg…ntegration:11753:32)
    at flush (plugin:obsidian-togg…integration:11724:7)
    at init (plugin:obsidian-togg…integration:12063:5)
    at new TogglReportBlock (plugin:obsidian-togg…integration:19461:5)
    at reportBlockHandler (plugin:obsidian-togg…integration:19471:3)
    at app.js:1:1286123
    at t.postProcess (app.js:1:1524045)
    at t.postProcess (app.js:1:1522873)
    at h (app.js:1:1273755)
    at e.onRender (app.js:1:1274015)
app.js:1 Uncaught 

TypeError: Cannot read properties of null (reading 'frontmatter')
    at isFmDisable (plugin:auto-note-mover:1806:68)
    at fileCheck (plugin:auto-note-mover:2079:13)
    at eval (plugin:auto-note-mover:2125:66)
    at e.tryTrigger (app.js:1:722881)
    at e.trigger (app.js:1:722814)
    at t.trigger (app.js:1:740919)
    at t.onChange (app.js:1:730983)
    at e.trigger (app.js:1:545440)
    at e.<anonymous> (app.js:1:543512)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at v (app.js:1:235994)
    at e.reconcileFileCreation (app.js:1:542989)
    at e.<anonymous> (app.js:1:542630)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
    
plugin:obsidian-toggl-integration:21138 Uncaught 
TypeError: Cannot read properties of undefined (reading 'p')
    at Object.p (plugin:obsidian-togg…ntegration:21138:45)
    at update (plugin:obsidian-togg…ntegration:11753:32)
    at flush (plugin:obsidian-togg…integration:11724:7)
    at init (plugin:obsidian-togg…integration:12063:5)
    at new TogglReportBlock (plugin:obsidian-togg…integration:19461:5)
    at reportBlockHandler (plugin:obsidian-togg…integration:19471:3)
    at t.initDOM (app.js:1:1766603)
    at t.toDOM (app.js:1:1223235)
    at t.sync (app.js:1:331514)
    at e.sync (app.js:1:313111)
    at app.js:1:354441
    at e.ignore (app.js:1:435059)
    at t.updateInner (app.js:1:354223)
    at t.update (app.js:1:353978)
    at e.update (app.js:1:443807)
    at e.dispatchTransactions (app.js:1:440368)
    at e.dispatch (app.js:1:442356)
    at Pr (app.js:1:380769)
    at Dr.paste (app.js:1:385278)
    at e.runHandlers (app.js:1:373760)
    at e.handleEvent (app.js:1:373522)
    
app.js:1 Uncaught 
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at t.measureVisibleLineHeights (app.js:1:361709)
    at e.measure (app.js:1:409182)
    at e.measure (app.js:1:446429)
    at e.readMeasured (app.js:1:449075)
    at e.coordsAtPos (app.js:1:452799)
    at e.updateDom (app.js:1:1189264)
    at r (app.js:1:518642)
    
plugin:obsidian-toggl-integration:21138 Uncaught 
TypeError: Cannot read properties of undefined (reading 'p')
    at Object.p (plugin:obsidian-togg…ntegration:21138:45)
    at update (plugin:obsidian-togg…ntegration:11753:32)
    at flush (plugin:obsidian-togg…integration:11724:7)
    at init (plugin:obsidian-togg…integration:12063:5)
    at new TogglReportBlock (plugin:obsidian-togg…integration:19461:5)
    at reportBlockHandler (plugin:obsidian-togg…integration:19471:3)
    at app.js:1:1286123
    at t.postProcess (app.js:1:1524045)
    at t.postProcess (app.js:1:1522873)
    at h (app.js:1:1273755)
    at e.onRender (app.js:1:1274015)

**Comment by farinasa** [comment]
Also seeing this issue, and the provided fix did not work.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at eval (plugin:obsidian-toggl-integration:18866:25)
    at Array.map (<anonymous>)
    at eval (plugin:obsidian-toggl-integration:18864:22)
    at sync (plugin:obsidian-toggl-integration:12749:22)
    at Array.eval (plugin:obsidian-toggl-integration:12760:9)
    at set3 (plugin:obsidian-toggl-integration:12708:35)
    at async Promise.all (index 0)
    at async TogglService._preloadWorkspaceData (plugin:obsidian-toggl-integration:20169:5)
    at async TogglService.setToken (plugin:obsidian-toggl-integration:20152:7)

Toggl API error:  Error: Toggl API responded with status code 403. Response: "Missing or invalid workspace_id" (API endpoint: workspaces/none/tags)
    at TogglClient.requestObsidian (plugin:obsidian-toggl-integration:19984:13)
    at async TogglClient.get (plugin:obsidian-toggl-integration:19929:12)
    at async Workspaces.tags (plugin:obsidian-toggl-integration:19626:27)
    at async TogglAPI.getTags (plugin:obsidian-toggl-integration:20050:19)
    at async Promise.all (index 1)
    at async TogglService._preloadWorkspaceData (plugin:obsidian-toggl-integration:20169:5)
    at async TogglService.setToken (plugin:obsidian-toggl-integration:20152:7)
handleError @ plugin:obsidian-toggl-integration:20121
plugin:obsidian-toggl-integration:20121 

Toggl API error:  Error: Toggl API responded with status code 403. Response: "Missing or invalid workspace_id" (API endpoint: workspaces/none/projects)
    at TogglClient.requestObsidian (plugin:obsidian-toggl-integration:19984:13)
    at async TogglClient.get (plugin:obsidian-toggl-integration:19929:12)
    at async Workspaces.projects (plugin:obsidian-toggl-integration:19620:27)
    at async TogglAPI.getProjects (plugin:obsidian-toggl-integration:20046:23)
    at async Promise.all (index 0)
    at async TogglService._preloadWorkspaceData (plugin:obsidian-toggl-integration:20169:5)
    at async TogglService.setToken (plugin:obsidian-toggl-integration:20152:7)
handleError @ plugin:obsidian-toggl-integration:20121
plugin:obsidian-toggl-integration:20047 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at TogglAPI.getProjects (plugin:obsidian-toggl-integration:20047:22)
    at async Promise.all (index 0)
    at async TogglService._preloadWorkspaceData (plugin:obsidian-toggl-integration:20169:5)
    at async TogglService.setToken (plugin:obsidian-toggl-integration:20152:7)
plugin:obsidian-toggl-integration:20121 

Toggl API error:  Error: Toggl API responded with status code 403. Response: "Missing or invalid workspace_id" (API endpoint: workspaces/none/clients)
    at TogglClient.requestObsidian (plugin:obsidian-toggl-integration:19984:13)
    at async TogglClient.get (plugin:obsidian-toggl-integration:19929:12)
    at async Workspaces.clients (plugin:obsidian-toggl-integration:19614:27)
    at async TogglAPI.getClients (plugin:obsidian-toggl-integration:20042:22)
    at async Promise.all (index 2)

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at eval (plugin:obsidian-toggl-integration:18866:25)
    at Array.map (<anonymous>)
    at eval (plugin:obsidian-toggl-integration:18864:22)
    at sync (plugin:obsidian-toggl-integration:12749:22)
    at Array.eval (plugin:obsidian-toggl-integration:12760:9)
    at set3 (plugin:obsidian-toggl-integration:12708:35)
    at async Promise.all (index 0)
    at async TogglService._preloadWorkspaceData (plugin:obsidian-toggl-integration:20169:5)
    at async TogglService.setToken (plugin:obsidian-toggl-integration:20152:7)
plugin:obsidian-toggl-integration:20221 Error reaching Toggl API
